/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.9.24")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.10.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.10.0")
    implementation(libs.guava)
    implementation ("org.apache.commons:commons-csv:1.12.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass.set("control.WortTrainerController")
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}
tasks.register<Copy>("copyResourcesToJarDir") {
    from("/woerter.csv")
    into("$buildDir/libs")
}

tasks.named("build") {
    finalizedBy("copyResourcesToJarDir")
}
tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "control.WortTrainerController"
    }
}
tasks.withType<Jar> {
    from(sourceSets.main.get().resources)
}
tasks.withType<Jar> {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from(sourceSets.main.get().resources)
}

