name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set executable permissions for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --info

      - name: Check build output
        run: ls -al build/libs

      - name: Generate Javadocs
        run: ./gradlew javadoc

      - name: Check Javadocs output
        run: ls -al build/docs/javadoc

      - name: Upload JAR file
        uses: actions/upload-artifact@v2
        with:
          name: my-jar
          path: build/libs/*.jar

      - name: Upload Javadocs
        uses: actions/upload-artifact@v2
        with:
          name: my-javadocs
          path: build/docs/javadoc/**
