name: Java CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set executable permissions for gradlew
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Tests
        run: ./gradlew test --warning-mode all

      - name: Debug Build Artifacts
        run: |
          echo "Listing root directory"
          ls -R
          echo "Listing build/libs"
          ls -R build/libs || echo "build/libs not found"
          echo "Listing build/docs/javadoc"
          ls -R build/docs/javadoc || echo "build/docs/javadoc not found"

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create Jar
        run: ./gradlew jar

      - name: Generate Javadocs
        run: ./gradlew javadoc

      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: my-java-app
          path: build/libs/*.jar

      - name: Upload Javadocs
        uses: actions/upload-artifact@v3
        with:
          name: javadocs
          path: build/docs/javadoc/**
